services:
  outpainting-server:
    container_name: outpainting-server
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.guethler.dev/outpainting-server:latest
    ports:
      - "8888:8888"
    volumes:
      - ./public:/app/public
